class CfgPatches
{
	class MET_P2_Units
	{
		units[]=
		{
			"MET_P2_TRP",
			"MET_P2_TRP2",
			"MET_P2_MED",
            "MET_P2_AR",
            "MET_P2_Z6",
            "MET_P2_GL",
            "MET_P2_CQC",
            "MET_P2_LAT",
            "MET_P2_HAT",
            "MET_P2_AA"
		};
		weapons[]={};
	};
};
class CfgWeapons
{
	class MET_DC15L_F;
	class MET_DC15L_F_NPC: MET_DC15L_F
	{
		scope=1;
		class LinkedItems
		{
			/*class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_hamr";
			};*/
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="3AS_Bipod_DC15L_f";
			};
			/*class LinkedItemsMuzzle
			{
				slot="MuzzleSlot";
				item="hdc_67_suppressor";
			};*/
		};
	};
	class MET_Valken38X_F;
	class MET_Valken38X_F_NPC: MET_Valken38X_F
	{
		scope=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="MET_Optic_VK38X";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="3AS_Bipod_VK38X_f";
			};
		};
	};
    class MET_DC15S;
	class MET_DC15S_NPC: MET_DC15S
	{
		scope=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="3AS_optic_holo_DC15S";
			};
		};
	};
};
class CfgVehicles
{
    class backpack_16th_medic;
    class backpack_16th_medic_npc: backpack_16th_medic
	{
		scope=1;
		class TransportItems
		{
			class _xx_kat_accuvac
			{
				count=1;
				name="kat_accuvac";
			};
			class _xx_ACE_personalAidKit
			{
				count=1;
				name="ACE_personalAidKit";
			};
			class _xx_kat_X_AED
			{
				count=1;
				name="kat_X_AED";
			};
			class _xx_ACE_plasmaIV
			{
				count=12;
				name="ACE_plasmaIV";
			};
			class _xx_ACE_plasmaIV_500
			{
				count=12;
				name="ACE_plasmaIV_500";
			};
			class _xx_ACE_painkillers
			{
				count=1;
				name="ACE_painkillers";
			};
			class _xx_LFP_item_injector_red
			{
				count=10;
				name="LFP_item_injector_red";
			};
			class _xx_LFP_item_bacta_bandage
			{
				count=100;
				name="LFP_item_bacta_bandage";
			};
			class _xx_ACE_splint
			{
				count=10;
				name="ACE_splint";
			};
			class _xx_ACE_tourniquet
			{
				count=30;
				name="ACE_tourniquet";
			};
            
		};
	};
    class backpack_16th_heavy;
    class backpack_16th_heavy_ar: backpack_16th_heavy
	{
		scope=1;
		class TransportItems
		{
			class _xx_MET_DC15L_mag
			{
				count=12;
				name="MET_DC15L_mag";
			};
		};
	};
    class backpack_16th_heavy_z6: backpack_16th_heavy
	{
		scope=1;
		class TransportItems
		{
			class _xx_MET_DC15L_mag
			{
				count=12;
				name="MET_blaster_battery";
			};
		};
	};
    class backpack_16th_heavy_lat: backpack_16th_heavy
	{
		scope=1;
		class TransportItems
		{
			class _xx_DBA_90mm_IK55_HEAT_x1_mag
			{
				count=6;
				name="DBA_90mm_IK55_HEAT_x1_mag";
			};
			class _xx_DBA_90mm_IK40_FRAG_x1_mag
			{
				count=3;
				name="DBA_90mm_IK40_FRAG_x1_mag";
			};
			class _xx_DBA_90mm_IK60_HEP_x1_mag
			{
				count=2;
				name="DBA_90mm_IK60_HEP_x1_mag";
			};
		};
	};
    class backpack_16th_heavy_hat: backpack_16th_heavy
	{
		scope=1;
		class TransportItems
		{
			class _xx_metal_at_mag
			{
				count=5;
				name="metal_at_mag";
			};
			class _xx_metal_ap_mag
			{
				count=2;
				name="metal_ap_mag";
			};
		};
	};
    class backpack_16th_heavy_aa: backpack_16th_heavy
	{
		scope=1;
		class TransportItems
		{
			class _xx_3AS_JLTS_MK39_AA
			{
				count=5;
				name="3AS_JLTS_MK39_AA";
			};
		};
	};
    class beltpack_16th;
    class backpack_16th_gl: beltpack_16th
	{
		scope=1;
		class TransportItems
		{
			class _xx_1Rnd_HE_Grenade_shell
			{
				count=20;
				name="1Rnd_HE_Grenade_shell";
			};
		};
	};
    class B_Soldier_base_F;
	class MET_P2_Base: B_Soldier_base_F
	{
		scope=1;
		faction="metal_company";
		editorSubCategory="metal_co_EdSubCat_p2";
		//editorPreview="\HDC_Units_mod\data\Editor Previews\WRU\HDC_WRU_Medic.jpg";
		side=1;
        //backpack="";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		Items[]=
		{
			"ACE_Flashlight_XL50",
			"ACE_EntrenchingTool",
			"ACE_CableTie",
			"ACE_CableTie",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_injector_red",
            "LFP_item_injector_red",
            "ACE_painkillers",
            "ACE_plasmaIV_500",
            "ACE_plasmaIV_500",
            "ACE_splint",
            "ACE_splint",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_MapTools"
		};
		respawnItems[]=
		{
			"ACE_Flashlight_XL50",
			"ACE_EntrenchingTool",
			"ACE_CableTie",
			"ACE_CableTie",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_injector_red",
            "LFP_item_injector_red",
            "ACE_painkillers",
            "ACE_plasmaIV_500",
            "ACE_plasmaIV_500",
            "ACE_splint",
            "ACE_splint",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_MapTools"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_basic",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_basic",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
	};
    class MET_P2_TRP: MET_P2_Base
	{
		scope=2;
		displayName="Trooper (DC-15A)";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_trooper.jpg";
		side=1;
        //backpack="";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
            "MET_DC15A_PLASTIC",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15A_PLASTIC",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
	};
    class MET_P2_TRP2: MET_P2_Base
	{
		scope=2;
		displayName="Trooper (DC-15S)";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_trooper_s.jpg";
		side=1;
        //backpack="";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
            "MET_DC15S_NPC",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15S_NPC",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
	};
    class MET_P2_MED: MET_P2_Base
	{
		scope=2;
		displayName="Medic";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_medic.jpg";
		side=1;
        backpack="backpack_16th_medic_npc";
		uniformClass="armor_16th_med";
		Weapons[]=
		{
            "MET_DC15S",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15S",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_medic",
			"vest_16_backpack_rack_cls",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
        respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_medic",
			"vest_16_backpack_rack_cls",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
	};
    class MET_P2_AR: MET_P2_Base
	{
		scope=2;
		displayName="Auto Rifleman";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_ar.jpg";
		side=1;
        backpack="backpack_16th_heavy_AR";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
            "MET_DC15L_F_NPC",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15L_F_NPC",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15L_mag",
            "MET_DC15L_mag",
            "MET_DC15L_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15L_mag",
            "MET_DC15L_mag",
            "MET_DC15L_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_ammo_bearer",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_ammo_bearer",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
	};
    class MET_P2_Z6: MET_P2_Base
	{
		scope=2;
		displayName="Machine Gunner";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_mg.jpg";
		side=1;
        backpack="backpack_16th_heavy_z6";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
            "MET_Z6",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_Z6",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_blaster_battery_green",
            "MET_blaster_battery",
            "MET_blaster_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_blaster_battery_green",
            "MET_blaster_battery",
            "MET_blaster_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_ammo_bearer",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_ammo_bearer",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
	};
    class MET_P2_GL: MET_P2_Base
	{
		scope=2;
		displayName="Grenadier";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_gl.jpg";
		side=1;
        backpack="backpack_16th_gl";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
            "MET_DC15A_ugl_plastic",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15A_ugl_plastic",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
	};
    class MET_P2_CQC: MET_P2_Base
	{
		scope=2;
		displayName="Trooper (CQC)";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_cqc.jpg";
		side=1;
        //backpack="";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
            "MET_JLTS_DP23",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_JLTS_DP23",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
	};
    class MET_P2_LAT: MET_P2_Base
	{
		scope=2;
		displayName="Light AT";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_lat.jpg";
		side=1;
        backpack="backpack_16th_heavy_LAT";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
            "MET_DC15S_NPC",
            "rps_16th",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15S_NPC",
            "rps_16th",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_at",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_at",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
	};
    class MET_P2_HAT: MET_P2_Base
	{
		scope=2;
		displayName="Heavy AT";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_hat.jpg";
		side=1;
        backpack="backpack_16th_heavy_HAT";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
            "MET_DC15S_NPC",
            "plx_16th",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15S_NPC",
            "plx_16th",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_at",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_at",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
	};
    class MET_P2_AA: MET_P2_Base
	{
		scope=2;
		displayName="Anti Air";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_hat.jpg";
		side=1;
        backpack="backpack_16th_heavy_AA";
		uniformClass="armor_16th_trp";
		Weapons[]=
		{
            "MET_DC15S_NPC",
            "MET_PLX1_AA",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15S_NPC",
            "MET_PLX1_AA",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_at",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"helmet_16th_trp",
			"vest_16_backpack_rack_at",
			"CWHUD_P2_base",
			"212th_JLTS_Clone_Helmet_NVG_Chip"
		};
	};
};