class CfgPatches
{
	class MET_P2_Units
	{
		units[]=
		{
			"MET_P2_TRP",
			"MET_P2_TRPDC15S",
			"MET_P2_MED",
            "MET_P2_AR",
            "MET_P2_Z6",
            "MET_P2_GL",
            "MET_P2_CQC",
            "MET_P2_LAT",
            "MET_P2_HAT",
            "MET_P2_AA"
		};
		weapons[]={};
	};
};
class CfgWeapons
{
	class MET_DC15L_F;
	class MET_DC15L_F_NPC: MET_DC15L_F
	{
		scope=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="MET_optic_DC15L_F";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="3AS_Bipod_DC15L_f";
			};
			/*class LinkedItemsMuzzle
			{
				slot="MuzzleSlot";
				item="hdc_67_suppressor";
			};*/
		};
	};
	class MET_Valken38X_F;
	class MET_Valken38X_F_NPC: MET_Valken38X_F
	{
		scope=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="MET_optic_VK38X_F";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="3AS_Bipod_VK38X_f";
			};
		};
	};
};
class CfgVehicles
{
    class MET_Backpack_Medic;
    class MET_Backpack_Medic_npc: MET_Backpack_Medic
	{
		scope=1;
		class TransportItems
		{
			class _xx_kat_accuvac
			{
				count=1;
				name="kat_accuvac";
			};
			class _xx_ACE_personalAidKit
			{
				count=1;
				name="ACE_personalAidKit";
			};
			class _xx_kat_X_AED
			{
				count=1;
				name="kat_X_AED";
			};
			class _xx_ACE_plasmaIV
			{
				count=12;
				name="ACE_plasmaIV";
			};
			class _xx_ACE_plasmaIV_500
			{
				count=12;
				name="ACE_plasmaIV_500";
			};
			class _xx_ACE_painkillers
			{
				count=1;
				name="ACE_painkillers";
			};
			class _xx_LFP_item_injector_red
			{
				count=10;
				name="LFP_item_injector_red";
			};
			class _xx_LFP_item_bacta_bandage
			{
				count=100;
				name="LFP_item_bacta_bandage";
			};
			class _xx_ACE_splint
			{
				count=10;
				name="ACE_splint";
			};
			class _xx_ACE_tourniquet
			{
				count=30;
				name="ACE_tourniquet";
			};
            
		};
	};
    class MET_Backpack_Base;
    class MET_Backpack_Heavy_ar: MET_Backpack_Base
	{
		scope=1;
		class TransportItems
		{
			class _xx_MET_DC15L_mag
			{
				count=12;
				name="MET_DC15L_mag";
			};
		};
	};
	class MET_Backpack_Heavy;
    class MET_Backpack_Heavy_z6: MET_Backpack_Heavy
	{
		scope=1;
		class TransportItems
		{
			class _xx_MET_DC15L_mag
			{
				count=12;
				name="MET_blaster_battery";
			};
		};
	};
    class MET_Backpack_Heavy_lat: MET_Backpack_Heavy
	{
		scope=1;
		class TransportItems
		{
			class _xx_DBA_90mm_IK55_HEAT_x1_mag
			{
				count=6;
				name="DBA_90mm_IK55_HEAT_x1_mag";
			};
			class _xx_DBA_90mm_IK40_FRAG_x1_mag
			{
				count=3;
				name="DBA_90mm_IK40_FRAG_x1_mag";
			};
			class _xx_DBA_90mm_IK60_HEP_x1_mag
			{
				count=2;
				name="DBA_90mm_IK60_HEP_x1_mag";
			};
		};
	};
    class MET_Backpack_Heavy_hat: MET_Backpack_Heavy
	{
		scope=1;
		class TransportItems
		{
			class _xx_metal_at_mag
			{
				count=5;
				name="metal_at_mag";
			};
			class _xx_metal_ap_mag
			{
				count=2;
				name="metal_ap_mag";
			};
		};
	};
    class MET_Backpack_Heavy_aa: MET_Backpack_Heavy
	{
		scope=1;
		class TransportItems
		{
			class _xx_metal_aa_alt_mag
			{
				count=5;
				name="metal_aa_alt_mag";
			};
		};
	};
    class MET_Beltbag_Base;
    class MET_Beltbag_Base_gl: MET_Beltbag_Base
	{
		scope=1;
		class TransportItems
		{
			class _xx_1Rnd_HE_Grenade_shell
			{
				count=20;
				name="1Rnd_HE_Grenade_shell";
			};
		};
	};
    class B_Soldier_base_F;
	class MET_P2_Base: B_Soldier_base_F
	{
		scope=1;
		faction="metal_company";
		editorSubCategory="metal_co_EdSubCat_p2";
		//editorPreview="\HDC_Units_mod\data\Editor Previews\WRU\HDC_WRU_Medic.jpg";
		side=1;
        //backpack="";
		uniformClass="MET_Uniform_Trooper";
		Weapons[]=
		{
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		Items[]=
		{
			"ACE_Flashlight_XL50",
			"ACE_EntrenchingTool",
			"ACE_CableTie",
			"ACE_CableTie",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_injector_red",
            "LFP_item_injector_red",
            "ACE_painkillers",
            "ACE_plasmaIV_500",
            "ACE_plasmaIV_500",
            "ACE_splint",
            "ACE_splint",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_MapTools"
		};
		respawnItems[]=
		{
			"ACE_Flashlight_XL50",
			"ACE_EntrenchingTool",
			"ACE_CableTie",
			"ACE_CableTie",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_bacta_bandage",
            "LFP_item_injector_red",
            "LFP_item_injector_red",
            "ACE_painkillers",
            "ACE_plasmaIV_500",
            "ACE_plasmaIV_500",
            "ACE_splint",
            "ACE_splint",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_tourniquet",
            "ACE_MapTools"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Basic",
			"MET_NVG_Integrated_Base"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Basic",
			"MET_NVG_Integrated_Base"
		};
	};
    class MET_P2_TRP: MET_P2_Base
	{
		scope=2;
		displayName="Trooper (DC-15A)";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_trooper.jpg";
		side=1;
        //backpack="";
		uniformClass="MET_Uniform_Trooper";
		Weapons[]=
		{
            "MET_DC15A_F",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15A_F",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
	};
    class MET_P2_TRPDC15S: MET_P2_Base
	{
		scope=2;
		displayName="Trooper (DC-15S)";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_trooper_s.jpg";
		side=1;
        //backpack="";
		Weapons[]=
		{
            "MET_DC15S_F",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15S_F",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
	};
    class MET_P2_MED: MET_P2_TRPDC15S
	{
		scope=2;
		displayName="Medic";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_medic.jpg";
		side=1;
        backpack="MET_Backpack_Medic_npc";
		uniformClass="MET_Uniform_Trooper_Medic";
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Medic",
			"MET_Vest_Rack_Medic",
			"MET_NVG_Integrated_Base"
		};
        respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Medic",
			"MET_Vest_Rack_Medic",
			"MET_NVG_Integrated_Base"
		};
	};
    class MET_P2_AR: MET_P2_Base
	{
		scope=2;
		displayName="Auto Rifleman";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_ar.jpg";
		side=1;
        backpack="MET_Backpack_Heavy_AR";
		Weapons[]=
		{
            "MET_DC15L_F_NPC",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15L_F_NPC",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15L_mag",
            "MET_DC15L_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15L_mag",
            "MET_DC15L_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_Ammo",
			"MET_NVG_Integrated_Base"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_Ammo",
			"MET_NVG_Integrated_Base"
		};
	};
    class MET_P2_Z6: MET_P2_Base
	{
		scope=2;
		displayName="Machine Gunner";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_mg.jpg";
		side=1;
        backpack="MET_Backpack_Heavy_z6";
		Weapons[]=
		{
            "MET_Z6_MkII",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_Z6_MkII",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_blaster_battery_green",
            "MET_blaster_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_blaster_battery_green",
            "MET_blaster_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_Ammo",
			"MET_NVG_Integrated_Base"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_Ammo",
			"MET_NVG_Integrated_Base"
		};
	};
    class MET_P2_GL: MET_P2_Base
	{
		scope=2;
		displayName="Grenadier";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_gl.jpg";
		side=1;
        backpack="MET_Beltbag_Base_gl";
		Weapons[]=
		{
            "MET_DC15A_ugl_plastic",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15A_ugl_plastic",
            "MET_DC17SA",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
            "MET_DC15A_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
	};
    class MET_P2_CQC: MET_P2_Base
	{
		scope=2;
		displayName="Trooper (CQC)";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_cqc.jpg";
		side=1;
        //backpack="";
		Weapons[]=
		{
            "MET_DP23_F",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DP23_F",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
            "MET_pellet_mag",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
	};
    class MET_P2_LAT: MET_P2_Base
	{
		scope=2;
		displayName="Light AT";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_lat.jpg";
		side=1;
        backpack="MET_Backpack_Heavy_LAT";
		Weapons[]=
		{
            "MET_DC15S_F",
            "rps_16th",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15S_F",
            "rps_16th",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_AT",
			"MET_NVG_Integrated_Base"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_AT",
			"MET_NVG_Integrated_Base"
		};
	};
    class MET_P2_HAT: MET_P2_Base
	{
		scope=2;
		displayName="Heavy AT";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_hat.jpg";
		side=1;
        backpack="MET_Backpack_Heavy_HAT";
		Weapons[]=
		{
            "MET_DC15S_F",
            "plx_16th",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15S_F",
            "plx_16th",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_AT",
			"MET_NVG_Integrated_Base"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_AT",
			"MET_NVG_Integrated_Base"
		};
	};
    class MET_P2_AA: MET_P2_Base
	{
		scope=2;
		displayName="Anti Air";
		editorSubCategory="metal_co_EdSubCat_p2";
		editorPreview="\z\16th\addons\units\data\Editor Previews\Phase2\p2_hat.jpg";
		side=1;
        backpack="MET_Backpack_Heavy_AA";
		Weapons[]=
		{
            "MET_DC15S_F",
            "MET_PLX1_AA",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
            "MET_DC15S_F",
            "MET_PLX1_AA",
            "MET_DC17S_F",
			"JLTS_CloneBinocular",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
		respawnMagazines[]=
		{
			"MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
            "MET_DC15S_mag",
			"MET_blaster_pistol_battery",
			"MET_blaster_pistol_battery",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Smoke_Blue",
			"MET_Smoke_Red",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Smoke_White"
		};
        linkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_AT",
			"MET_NVG_Integrated_Base"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemAndroid",
			"ItemCompass",
			"JLTS_clone_comlink",
			"ACE_Altimeter",
			"MET_Helmet_Trooper_Base",
			"MET_Vest_Rack_AT",
			"MET_NVG_Integrated_Base"
		};
	};
};