name = "The 16th Metal Company Aux Mod v2"
prefix = "16th"
mainprefix = "z"

[build]
addons_directory = "addons"

[properties]
author = "16th Modding Team"

[hemtt.release]
sign = true

[files]
include = [
    "16th_logo.paa",
    "mod.cpp",
    "addons/442_weapons.pbo",
    "addons/Indecisive_Armoury_Ammos.pbo",
    "addons/Kobra.pbo",
    "addons/WBK_HeavyWeaponsFramework.pbo",
]

[version]
major = 3
minor = 9
patch = 2