class CfgPatches
{
	class metal_rep_ammo_glheat
	{
		author="";
		requiredVersion=0.1;
		units[]={};
		ammo[]=
		{
			"MET_HEAT_LauncherGrenade",
			"MET_25HEAT_LauncherGrenade",
			"MET_60HEAT"
		};
		requiredAddons[]=
		{
			"metal_weapons",
			"metal_rep_ammo",
			"metal_rep_ammo_base",
			"metal_rep_ammo_glcore"
		};
	};
};
class CfgAmmo
{
	class MET_HE_LauncherGrenade;
	class MET_HEAT_LauncherGrenade: MET_HE_LauncherGrenade
	{
		ace_frag_enabled=0;
		explosionSoundEffect="DefaultExplosion";
		simulation="shotShell";
		model="Indecisive_Armoury_Ammos\Data\40mm_Grenade\IDA_40mm_Grenade.p3d";
		effectflare="FlareShell";
		effectfly="MET_GrenadeBlasterBoltGlow_Yellow_Fly";
		lightcolor[]={.839,0.749,0.486};
		hit=650;
		indirectHit=9;
		indirectHitRange=1;
		warheadName="HEAT";
		visibleFire=1;
		audibleFire=30;
		visibleFireTime=3;
		dangerRadiusHit=60;
		suppressionRadiusHit=24;
		explosive=0.40000001;
		cost=10;
		deflecting=5;
		airFriction=-0.001;
		fuseDistance=5;
		whistleDist=20;
		typicalSpeed=185;
		caliber=3;
		soundHit1[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01",
			3.1622777,
			1,
			1500
		};
		soundHit2[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02",
			3.1622777,
			1,
			1500
		};
		soundHit3[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03",
			3.1622777,
			1,
			1500
		};
		soundHit4[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04",
			3.1622777,
			1,
			1500
		};
		multiSoundHit[]=
		{
			"soundHit1",
			0.25,
			"soundHit2",
			0.25,
			"soundHit3",
			0.25,
			"soundHit4",
			0.25
		};
		class CamShakeExplode
		{
			power=4;
			duration=0.80000001;
			frequency=20;
			distance=75.7771;
		};
		class CamShakeHit
		{
			power=25;
			duration=0.40000001;
			frequency=20;
			distance=1;
		};
		class CamShakeFire
		{
			power=0;
			duration=0.2;
			frequency=20;
			distance=0;
		};
		class CamShakePlayerFire
		{
			power=0;
			duration=0.1;
			frequency=20;
			distance=1;
		};
	};
	class MET_25HE_LauncherGrenade;
	class MET_25HEAT_LauncherGrenade: MET_25HE_LauncherGrenade
	{
		ace_frag_enabled=0;
		explosionSoundEffect="DefaultExplosion";
		simulation="shotShell";
		model="Indecisive_Armoury_Ammos\Data\40mm_Grenade\IDA_40mm_Grenade.p3d";
		effectflare="FlareShell";
		effectfly="MET_SmallGrenadeBlasterBoltGlow_Yellow_Fly";
		lightcolor[]={.839,0.749,0.486};
		hit=350;
		indirectHit=5;
		indirectHitRange=1;
		warheadName="HEAT";
		visibleFire=1;
		audibleFire=30;
		visibleFireTime=3;
		dangerRadiusHit=60;
		suppressionRadiusHit=24;
		explosive=0.40000001;
		cost=10;
		deflecting=5;
		airFriction=-0.001;
		fuseDistance=5;
		whistleDist=20;
		typicalSpeed=185;
		caliber=2.5;
		soundHit1[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01",
			3.1622777,
			1,
			1500
		};
		soundHit2[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02",
			3.1622777,
			1,
			1500
		};
		soundHit3[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03",
			3.1622777,
			1,
			1500
		};
		soundHit4[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04",
			3.1622777,
			1,
			1500
		};
		multiSoundHit[]=
		{
			"soundHit1",
			0.25,
			"soundHit2",
			0.25,
			"soundHit3",
			0.25,
			"soundHit4",
			0.25
		};
		class CamShakeExplode
		{
			power=4;
			duration=0.80000001;
			frequency=20;
			distance=75.7771;
		};
		class CamShakeHit
		{
			power=25;
			duration=0.40000001;
			frequency=20;
			distance=1;
		};
		class CamShakeFire
		{
			power=0;
			duration=0.2;
			frequency=20;
			distance=0;
		};
		class CamShakePlayerFire
		{
			power=0;
			duration=0.1;
			frequency=20;
			distance=1;
		};
	};
	class ammo_Penetrator_Base;
	class MET_60HEAT_Penetrator: ammo_Penetrator_Base
	{
		hit=950;
		warheadName="TandemHEAT";
		caliber=20;
	};
	class MET_60HEAT: MET_HEAT_LauncherGrenade
	{
		ace_frag_enabled=1;
		ace_frag_metal=212;
		ace_frag_charge=38;
		ace_frag_gurney_c=2830;
		ace_frag_gurney_k="3/5";
		ace_frag_classes[]=
		{
			"ACE_frag_tiny_HD"
		};
		ace_frag_skip=0;
		ace_frag_force=1;
		explosionSoundEffect="";
		SoundSetExplosion[]=
		{
			"Mortar_Exp_SoundSet"
		};
		simulation="shotShell";
		effectFly="MET_GrenadeBlasterBoltGlow_Yellow_Fly";
		lightcolor[]={0,0,1};
		model="Indecisive_Armoury_Ammos\Data\40mm_Grenade\IDA_40mm_Grenade.p3d";
		aiAmmoUsageFlags="64";
		tracerScale=1.6;
		tracerStartTime=0.1;
		tracerEndTime=20;
		brightness=100000;
		hit=350;
		indirectHit=20;
		explosionForceCoef=5;
		indirectHitRange=3.5;
		warheadName="HE";
		visibleFire=1;
		audibleFire=30;
		visibleFireTime=3;
		dangerRadiusHit=60;
		suppressionRadiusHit=24;
		explosive=1;
		cost=25;
		deflecting=0;
		airFriction=-0.0049999999;
		fuseDistance=0;
		whistleDist=16;
		typicalSpeed=10;
		caliber=2;
		timeToLive=15;
		submunitionAmmo="MET_60HEAT_Penetrator";
		submunitionDirectionType="SubmunitionModelDirection";
		submunitionInitSpeed=1000;
		triggerOnImpact=1;
		submunitionParentSpeedCoef=1;
		deleteParentWhenTriggered=0;
		submunitionInitialOffset[]={0,0,-0.2};
		soundHit1[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01",
			1.1622777,
			1.4,
			1500
		};
		soundHit2[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02",
			1.1622777,
			1.4,
			1500
		};
		soundHit3[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03",
			1.1622777,
			1.4,
			1500
		};
		soundHit4[]=
		{
			"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04",
			1.1622777,
			1.4,
			1500
		};
		multiSoundHit[]=
		{
			"soundHit1",
			0.25,
			"soundHit2",
			0.25,
			"soundHit3",
			0.25,
			"soundHit4",
			0.25
		};
		class CamShakeExplode
		{
			power=8;
			duration=1.2;
			frequency=20;
			distance=74.596397;
		};
		class CamShakeHit
		{
			power=20;
			duration=0.40000001;
			frequency=20;
			distance=1;
		};
		class CamShakeFire
		{
			power=0;
			duration=0.2;
			frequency=20;
			distance=0;
		};
		class CamShakePlayerFire
		{
			power=0;
			duration=0.1;
			frequency=20;
			distance=1;
		};
	};
};