name: Release Mod

on:
  push:
    branches: [ release ]

jobs:
  windows:
    runs-on: windows-latest
    steps:   
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1

    - name: Build Mod
      run: hemtt release

    - name: Rename build folder
      run: mv .hemttout/build .hemttout/16th-Metal-Auxiliary-Mod

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
          name: 16th-Metal-Auxiliary-Mod
          path: .hemttout//16th-Metal-Auxiliary-Mod.zip
          include-hidden-files: true

    - name: Publish to Steam Workshop
      uses: gruppe-adler/action-release-to-steam-ws@v1
      with:
          file_id: 1234567890
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          path: ${{ steps.build.outputs.release_path }}/@${{ steps.build.outputs.mod_name }}
          name: ${{ steps.build.outputs.mod_name }}
          change_notes_title: ${{ github.event.release.name }}
          change_notes: ${{ github.event.release.body }}
