name: Release Mod
on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Run HEMTT build
        run: hemtt release

      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
            name: my-mod-latest
            path: release/my-mod-latest.zip

      - name: Publish to Steam Workshop
        uses: gruppe-adler/action-release-to-steam-ws@v1
        with:
          file_id: 1234567890
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          path: ${{ steps.build.outputs.release_path }}/@${{ steps.build.outputs.mod_name }}
          name: ${{ steps.build.outputs.mod_name }}
          change_notes_title: ${{ github.event.release.name }}
          change_notes: ${{ github.event.release.body }}
