name: Release Mod

on:
  push:
    branches: [ release ]

jobs:
  windows:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:   
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1

    - name: Track Version
      id: get_version
      shell: pwsh
      run: |
        $lines = Get-Content ".hemtt\project.toml"
        $major = ($lines | Select-String '^major\s*=\s*(\d+)').Matches.Groups[1].Value
        $minor = ($lines | Select-String '^minor\s*=\s*(\d+)').Matches.Groups[1].Value
        $patch = ($lines | Select-String '^patch\s*=\s*(\d+)').Matches.Groups[1].Value

        $version = "$major.$minor.$patch"
        Write-Host "Extracted version=$version"

        env:
          mod_version: $version

    - name: Build Mod
      run: hemtt release

    - name: Rename Release folder
      run: mv .hemttout/release .hemttout/16th-Metal-Auxiliary-Mod/

    - name: Zip Release Folder
      shell: pwsh
      run: |
        Write-Host "Zipping with version=mod_version"
          
        Compress-Archive -Path ".hemttout/16th-Metal-Auxiliary-Mod" `
                        -DestinationPath "16th-Metal-Auxiliary-Mod-v$(mod_version).zip"
          
        dir *.zip

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v$mod_version
        release_name: "16th Metal Auxiliary Mod v$mod_versionn"
        body: "Automated release of MyMod"
        draft: false
        prerelease: false

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "16th-Metal-Auxiliary-Mod-v$mod_version}.zip"
        asset_name: "16th-Metal-Auxiliary-Mod-v$mod_version}.zip"
        asset_content_type: "application/zip"
    
    - name: Publish to Steam Workshop
      uses: gruppe-adler/action-release-to-steam-ws@v1
      with:
          file_id: 1234567890
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          path: ${{ steps.build.outputs.release_path }}/@${{ steps.build.outputs.mod_name }}
          name: ${{ steps.build.outputs.mod_name }}
          change_notes_title: ${{ github.event.release.name }}
          change_notes: ${{ github.event.release.body }}