class CfgPatches
{
	class BHA_Acolytes
	{
		units[]=
		{
			"BHA_Acolytes_Acolyte",
			"BHA_Acolytes_Farseer",
			"BHA_Acolytes_Wayfarer",
			"BHA_Acolytes_Oracle",
			"BHA_Acolytes_Pacifier",
			"BHA_Acolytes_Mender",
			"BHA_Acolytes_Annihilator",
			"BHA_Acolytes_Obliterator",
			"BHA_Acolytes_Bishop"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class I_Soldier_base_F;
	class BHA_Acolytes_Base: I_Soldier_base_F
	{
		side=2;
		scope=0;
		scopeCurator=0;
		faction="BHA_Units";
		editorSubCategory="BHA_Acolytes";
		uniformClass="SC_Undersuit_Black";
		backpack="MET_MDFBackpack_Black";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		Weapons[]=
		{
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		Items[]=
		{
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"ACE_CableTie",
			"ACE_CableTie",
			"ACE_CableTie",
			"LFP_Skirata_Knife"
		};
		respawnItems[]=
		{
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"ACE_CableTie",
			"ACE_CableTie",
			"ACE_CableTie",
			"LFP_Skirata_Knife"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black"
		};
	};
	class BHA_Acolytes_Acolyte: BHA_Acolytes_Base
	{
		displayName="Acolyte";
		scope=2;
		scopeCurator=2;
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Acolyte.jpg";
		Weapons[]=
		{
			"MET_DLA13_C",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_C",
			"Put",
			"Throw"
		};
	};
	class BHA_Acolytes_Farseer: BHA_Acolytes_Base
	{
		displayName="Acolyte Farseer";
		scope=2;
		scopeCurator=2;
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Farseer.jpg";
		Weapons[]=
		{
			"MET_DLA13",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13",
			"Put",
			"Throw"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFRecon"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFRecon"
		};
	};
	class BHA_Acolytes_Wayfarer: BHA_Acolytes_Base
	{
		displayName="Acolyte Wayfarer";
		scope=2;
		scopeCurator=2;
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Wayfarer.jpg";
		Weapons[]=
		{
			"MET_DLA13_ugl",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_ugl",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_light_proton_mag",
			"MET_light_proton_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_light_proton_mag",
			"MET_light_proton_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFGrenadier"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFGrenadier"
		};
	};
	class BHA_Acolytes_Oracle: BHA_Acolytes_Base
	{
		displayName="Acolyte Oracle";
		scope=2;
		scopeCurator=2;
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Oracle.jpg";
		Weapons[]=
		{
			"MET_X300_Sniper",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_X300_Sniper",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFRecon"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFRecon"
		};
	};
	class BHA_Acolytes_Pacifier: BHA_Acolytes_Base
	{
		displayName="Acolyte Pacifier";
		scope=2;
		scopeCurator=2;
		icon="iconManMG";
		backpack="MET_MDFMGBackpack_Black";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Pacifier.jpg";
		Weapons[]=
		{
			"MET_EL34",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_EL34",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_EL34_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_EL34_mag",
			"MET_EL34_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFmgkit"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFmgkit"
		};
	};
	class BHA_Acolytes_Mender: BHA_Acolytes_Base
	{
		displayName="Acolyte Mender";
		scope=2;
		scopeCurator=2;
		icon="iconManMedic";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Mender.jpg";
		backpack="MET_MDFMedicBackpack_Black";
		Weapons[]=
		{
			"MET_DLA13_C",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_C",
			"Put",
			"Throw"
		};
	};
	class BHA_Acolytes_Annihilator: BHA_Acolytes_Base
	{
		displayName="Acolyte Annihilator";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Annihilator.jpg";
		backpack="MET_MDFATBackpack_Black";
		Weapons[]=
		{
			"MET_DLA13_C",
			"MET_HH12_SMRT",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_C",
			"MET_HH12_SMRT",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Acolytes_Obliterator: BHA_Acolytes_Base
	{
		displayName="Acolyte Obliterator";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Obliterator.jpg";
		backpack="MET_MDFAABackpack_Black";
		Weapons[]=
		{
			"MET_DLA13_C",
			"MET_HH12_SMRT",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_C",
			"MET_HH12_SMRT",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"BHA_AA_SINGLE",
			"BHA_AA_SINGLE",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"BHA_AA_SINGLE",
			"BHA_AA_SINGLE",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Acolytes_Bishop: BHA_Acolytes_Base
	{
		displayName="Acolyte Bishop";
		scope=2;
		scopeCurator=2;
		icon="iconManLeader";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Bishop.jpg";
		Weapons[]=
		{
			"MET_T20_rifle",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_T20_rifle",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
};
class CfgGroups
{
	class INDEP
	{
		class BHA_Units
		{
			name="Barysaw Holdings Authority";
			class BHA_Acolytes_inf_Groups
			{
				name="Acolyte Infantry Groups";
				class BHA_Acolytes_Squad
				{
					name="Squad";
					scope=2;
					side=2;
					faction="BHA_Units";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Unit0
					{
						side=2;
						vehicle="BHA_Acolytes_Bishop";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=2;
						vehicle="BHA_Acolytes_Farseer";
						rank="PRIVATE";
						position[]={1,-2,0};
					};
					class Unit2
					{
						side=2;
						vehicle="BHA_Acolytes_Wayfarer";
						rank="CORPORAL";
						position[]={-1,-2,0};
					};
					class Unit3
					{
						side=2;
						vehicle="BHA_Acolytes_Oracle";
						rank="CORPORAL";
						position[]={1,-3,0};
					};
					class Unit4
					{
						side=2;
						vehicle="BHA_Acolytes_Pacifier";
						rank="CORPORAL";
						position[]={-1,-3,0};
					};
					class Unit5
					{
						side=2;
						vehicle="BHA_Acolytes_Mender";
						rank="CORPORAL";
						position[]={1,-4,0};
					};
					class Unit6
					{
						side=2;
						vehicle="BHA_Acolytes_Annihilator";
						rank="CORPORAL";
						position[]={-1,-4,0};
					};
					class Unit7
					{
						side=2;
						vehicle="BHA_Acolytes_Obliterator";
						rank="CORPORAL";
						position[]={1,-5,0};
					};
					class Unit8
					{
						side=2;
						vehicle="BHA_Acolytes_Acolyte";
						rank="CORPORAL";
						position[]={-1,-5,0};
					};
				};
			};
		};
	};
};
class cfgMods
{
	author="";
	timepacked="1664364859";
};
